export const GET_COVID_G_DATA = 'GET_COVID_G_DATA';
export const GET_COVID_S_DATA = 'GET_COVID_S_DATA';
export const GET_TOTAL_NUMBERS_FOR_COUNTRY = 'GET_TOTAL_NUMBERS_FOR_COUNTRY';
export const ERROR = 'ERROR';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const LOADING = 'LOADING';
export const CLEAR_COVID_COUNTRY = 'CLEAR_COVID_COUNTRY';